
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_mysql
                host:     "%env(string:MYSQL_HOST)%"
                port:     "%env(string:MYSQL_PORT)%"
                dbname:   "%env(string:MYSQL_DATABASE)%"
                user:     "%env(string:MYSQL_USER)%"
                password: "%env(string:MYSQL_PASSWORD)%"
                logging: false
            clickhouse:
                host:     "%env(string:CLICKHOUSE_HOST)%"
                port:     "%env(string:CLICKHOUSE_PORT)%"
                user:     "%env(string:CLICKHOUSE_USER)%"
                password: "%env(string:CLICKHOUSE_PASSWORD)%"
                dbname:   "%env(string:CLICKHOUSE_DATABASE)%"
                driver_class: FOD\DBALClickHouse\Driver
                wrapper_class: FOD\DBALClickHouse\Connection
                options:
                    enable_http_compression: 1
                    max_execution_time: 60

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
#        entity_managers:
#            default:
        metadata_cache_driver:
            type: 'service'
            id: doctrine.cache.memcached
        query_cache_driver:
            type: 'service'
            id: doctrine.cache.memcached
        result_cache_driver:
            type: 'service'
            id: doctrine.cache.memcached