# http service configuration.
http:
  # http host to listen.
  address: 0.0.0.0:8080

  # max POST request size, including file uploads in MB.
  maxRequestSize: 200

  # file upload configuration.
  uploads:
    # list of file extensions which are forbidden for uploading.
    forbid: [".php", ".exe", ".bat"]

  # cidr blocks which can set ip using X-Real-Ip or X-Forwarded-For
  trustedSubnets: ["10.0.0.0/8", "127.0.0.0/8", "172.16.0.0/12", "172.17.0.0/12", "192.168.0.0/16", "::1/128", "fc00::/7", "fe80::/10"]

  # http worker pool configuration.
  workers:
    # php worker command.
    command:  "php roadrunner_worker.php pipes"

    # connection method (pipes, tcp://:9000, unix://socket.unix). default "pipes"
    relay:    "pipes"

    # worker pool configuration.
    pool:
      # number of workers to be serving.
      numWorkers: 10

      # maximum jobs per worker, 0 - unlimited.
      maxJobs:  1000

      # for how long worker is allowed to be bootstrapped.
      allocateTimeout: 60

      # amount of time given to the worker to gracefully destruct itself.
      destroyTimeout:  60

# monitors rr server(s)
limit:
  # check worker state each second
  interval: 1

  # custom watch configuration for each service
  services:
    # monitor HTTP workers
    http:
      # maximum allowed memory consumption per worker (soft)
      maxMemory: 128

      # maximum time to live for the worker (soft)
      TTL: 20

      # maximum allowed amount of time worker can spend in idle before being removed (for weak db connections, soft)
      idleTTL: 10

      # max_execution_time (brutal)
      execTTL: 5